AWSTemplateFormatVersion: '2010-09-09'
Description: Onica DevOps Test 2.1 S3 Stack
Parameters:
  Env:
    Type: String
    Default: sandbox
    AllowedValues:
      - prod
      - nonprod
      - sandbox
    Description: 'Deployment Environment'

  ContactInfo:
    Type: String
    Default: 'Client Group'
    Description: 'Contact for Client'

  ContactEmail:
    Type: String
    Default: 'clientgroup@company.info'
    Description: 'Contact email for Client'

Mappings:
  MapRegion:
    us-east-1:
      Name: ue1
    us-west-2:
      Name: uw2
  BPS3:
    us-east-1:
      ELBID: 127311923021
    us-west-2:
      ELBID: 797873946194

Resources:
  ClientS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
      - '-'
      - -  'client-s3'
        -  !FindInMap [MapRegion, !Ref 'AWS::Region', Name]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: client-s3
        - Key: ContactInfo
          Value: !Ref ContactInfo
        - Key: ContactEmail
          Value: !Ref ContactEmail
        - Key: Environment
          Value: !Ref Env
        - Key: Tool
          Value: CFN

  BucketPol:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ClientS3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:Put*
              - s3:Get*
              - s3:List*
            Principal:
              AWS: !Ref AWS::AccountId
            Resource:
              - !GetAtt ClientS3.Arn
              - !Join ['', [!GetAtt ClientS3.Arn, '/*']]
          - Effect: Deny
            Action: 's3:*'
            Principal: '*'
            Resource:
              - !GetAtt ClientS3.Arn
              - !Join ['', [!GetAtt ClientS3.Arn, '/*']]
            Condition:
              Bool:
                aws:SecureTransport: false
          - Effect: Allow
            Action: 's3:PutObject'
            Principal:
              AWS: !FindInMap [BPS3, !Ref 'AWS::Region', ELBID]
            Resource:
              - !Join ['', [!GetAtt ClientS3.Arn, '/', !Ref Env, '/AWSLogs/', !Ref 'AWS::AccountId', '/*']]
